/*
 * Stats API for the Battlefield series
 *
 * This project also has a <a href=\"https://top.gg/bot/714524944783900794\" target=\"_blank\">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href=\"https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html\" target=\"_blank\">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href=\"https://www.bf2hub.com\" target=\"_blank\">BF2Hub</a> and <a href=\"https://playbf2.tilda.ws/en\" target=\"_blank\">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href=\"https://battlefield2142.co/\" target=\"_blank\">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href=\"https://discord.gg/zMuxW6c\" target=\"_blank\">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href=\"https://github.com/sponsors/community-network\" target=\"_blank\">becoming a sponsor on GitHub</a>.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bf2042ServerInfo {
    #[serde(rename = "serverName")]
    pub server_name: String,
    #[serde(rename = "configDescription")]
    pub config_description: String,
    #[serde(rename = "configName")]
    pub config_name: String,
    #[serde(rename = "serverDescription")]
    pub server_description: String,
    #[serde(rename = "messages")]
    pub messages: Vec<models::Bf2042ServerMessages>,
}

impl Bf2042ServerInfo {
    pub fn new(server_name: String, config_description: String, config_name: String, server_description: String, messages: Vec<models::Bf2042ServerMessages>) -> Bf2042ServerInfo {
        Bf2042ServerInfo {
            server_name,
            config_description,
            config_name,
            server_description,
            messages,
        }
    }
}

