/*
 * Stats API for the Battlefield series
 *
 * This project also has a <a href=\"https://top.gg/bot/714524944783900794\" target=\"_blank\">Discord bot</a>, allowing anyone in your server to check their Battlefield stats via simple commands.<br><br>Language tags (lang) for both Battlefield 1 and Battlefield 5 are based on <a href=\"https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html\" target=\"_blank\">Java 8 language tags.</a> (response keys do not change based on the language tags, only the values do).<br><br>Data for Battlefield 2 is retrieved from the two revive projects: <a href=\"https://www.bf2hub.com\" target=\"_blank\">BF2Hub</a> and <a href=\"https://playbf2.tilda.ws/en\" target=\"_blank\">PlayBF2</a>.<br><br>Data for Battlefield 2142 is retrieved from the <a href=\"https://battlefield2142.co/\" target=\"_blank\">BF2142 Reclamation</a> project.<br><br>All other titles are still managed by EA/Dice.<br><br>If you discover any issues or have suggestions for new features, post them in the Community Network Discord: <a href=\"https://discord.gg/zMuxW6c\" target=\"_blank\">discord.gg/zMuxW6c</a>.<br><br>If you want to support the project, consider <a href=\"https://github.com/sponsors/community-network\" target=\"_blank\">becoming a sponsor on GitHub</a>.
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultipleWeaponInfo {
    #[serde(rename = "weaponName")]
    pub weapon_name: String,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kills")]
    pub kills: i32,
    #[serde(rename = "accuracy")]
    pub accuracy: String,
    #[serde(rename = "killsPerMinute")]
    pub kills_per_minute: i32,
    #[serde(rename = "hitVKills")]
    pub hit_v_kills: i32,
    #[serde(rename = "shotsHit")]
    pub shots_hit: i32,
    #[serde(rename = "shotsFired")]
    pub shots_fired: i32,
    #[serde(rename = "timeEquipped")]
    pub time_equipped: i32,
}

impl MultipleWeaponInfo {
    pub fn new(weapon_name: String, id: String, kills: i32, accuracy: String, kills_per_minute: i32, hit_v_kills: i32, shots_hit: i32, shots_fired: i32, time_equipped: i32) -> MultipleWeaponInfo {
        MultipleWeaponInfo {
            weapon_name,
            id,
            kills,
            accuracy,
            kills_per_minute,
            hit_v_kills,
            shots_hit,
            shots_fired,
            time_equipped,
        }
    }
}

